<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net45;net451;net452;net46;net461;net462;net47;net471;net472;net48;net481;netcoreapp3.1;net6.0;net8.0;net10.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<RootNamespace>Root.Reports</RootNamespace>
		<AssemblyName>Reports</AssemblyName>
		<MapFileExtensions>true</MapFileExtensions>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<DefineConstants>TRACE;DEBUG;Framework2;Compatible_0_8x</DefineConstants>
		<DocumentationFile>bin\Debug\$(TargetFramework)\Reports.XML</DocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<DefineConstants>TRACE;Framework2;Compatible_0_8x</DefineConstants>
		<DocumentationFile>bin\Release\$(TargetFramework)\Reports.XML</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="PDF\afm\Courier-Bold.afm" />
		<EmbeddedResource Include="PDF\afm\Courier-BoldOblique.afm" />
		<EmbeddedResource Include="PDF\afm\Courier-Oblique.afm" />
		<EmbeddedResource Include="PDF\afm\Courier.afm" />
		<EmbeddedResource Include="PDF\afm\Helvetica-Bold.afm" />
		<EmbeddedResource Include="PDF\afm\Helvetica-BoldOblique.afm" />
		<EmbeddedResource Include="PDF\afm\Helvetica-Oblique.afm" />
		<EmbeddedResource Include="PDF\afm\Helvetica.afm" />
		<EmbeddedResource Include="PDF\afm\Symbol.afm" />
		<EmbeddedResource Include="PDF\afm\Times-Bold.afm" />
		<EmbeddedResource Include="PDF\afm\Times-BoldItalic.afm" />
		<EmbeddedResource Include="PDF\afm\Times-Italic.afm" />
		<EmbeddedResource Include="PDF\afm\Times-Roman.afm" />
		<EmbeddedResource Include="PDF\afm\ZapfDingbats.afm" />
		<EmbeddedResource Include="PDF\afm\Arial.afm" />
		<EmbeddedResource Include="PDF\afm\Arial-Bold.afm" />
		<EmbeddedResource Include="PDF\afm\Arial-Italic.afm" />
		<EmbeddedResource Include="PDF\afm\Arial-BoldItalic.afm" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="PDF\afm\MustRead.html" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="PDF\PdfFontData.cs" />
		<Compile Remove="PDF\PdfFontDefX.cs" />
		<Compile Remove="PDF\PdfFontPropX.cs" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
		<PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0' or '$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.Windows.Compatibility" Version="8.0.11" />
	</ItemGroup>

	<ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
		<Reference Include="System.Drawing" />
		<Reference Include="System.Web" />
		<Reference Include="System.Windows.Forms" />
	</ItemGroup>
</Project>